---
# tasks file for docker
- name: Provision Docker
  hosts: all
  become: true

  tasks:
    - name: Ensure docker.io and pip packages are present
      apt: name={{ item }} state=present
        state: present
        update_cache: true # Do it once for all
      with_items:
        - docker.io
        - python-pip

    - name: Ensure pip docker-py package is installed
      pip:
        name: docker-py
        state: present