---
# tasks file for prod
- name: Pull and run the Docker image of boxfuse
  docker_container:
    name: boxfuse
    image: "{{ image_name }}:latest"
    ports: 8080:8080
    pull: true
    detach: true
    state: started
  notify:
    - Stop Tomcat on the host
  register: result
  failed_when: "Could not find the requested service tomcat9" not in result.stdout