---
# tasks file for prod
- name: Pull and run the Docker image of boxfuse
  docker_container:
    name: boxfuse
    image: {{ image_name }}/lsn8:latest
    ports: 8080:8080
    pull: true
    detach: true
    state: started
    notify:
      - Stop Tomcat on the host